"""Add auth0_user_id to users table

Revision ID: 6a75598faec9
Revises: eb3581ec218f
Create Date: 2025-06-27 10:05:05.919356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a75598faec9'
down_revision: Union[str, None] = 'eb3581ec218f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth0_user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_auth0_user_id'), 'users', ['auth0_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth0_user_id'), table_name='users')
    op.drop_column('users', 'auth0_user_id')
    # ### end Alembic commands ###
